In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from pandas import Series,DataFrame

In [4]:
data = pd.read_csv('Salary_Data.csv')

In [5]:
data

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [6]:
data.head()    #Shows some starting values of data

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [7]:
x = data.iloc[:,:1].values

In [8]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [9]:
l = [0,1,2,3,4]  #for reference

In [10]:
l[0:2]    #for reference

[0, 1]

In [11]:
y = data.iloc[:,1].values

In [12]:
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size =0.25,random_state=0)

In [15]:
x_train

array([[ 5.3],
       [ 7.9],
       [ 2.9],
       [ 5.1],
       [ 3.2],
       [ 4.5],
       [ 8.2],
       [ 6.8],
       [ 1.3],
       [10.5],
       [ 3. ],
       [ 2.2],
       [ 5.9],
       [ 6. ],
       [ 3.7],
       [ 3.2],
       [ 9. ],
       [ 2. ],
       [ 1.1],
       [ 7.1],
       [ 4.9],
       [ 4. ]])

In [16]:
x_test

array([[ 1.5],
       [10.3],
       [ 4.1],
       [ 3.9],
       [ 9.5],
       [ 8.7],
       [ 9.6],
       [ 4. ]])

In [17]:
y_train

array([ 83088., 101302.,  56642.,  66029.,  64445.,  61111., 113812.,
        91738.,  46205., 121872.,  60150.,  39891.,  81363.,  93940.,
        57189.,  54445., 105582.,  43525.,  39343.,  98273.,  67938.,
        56957.])

In [18]:
y_test

array([ 37731., 122391.,  57081.,  63218., 116969., 109431., 112635.,
        55794.])

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
regressor = LinearRegression()

In [21]:
regressor.fit(x_train,y_train)

LinearRegression()

# testing

In [22]:
y_pred = regressor.predict(x_test)   

In [23]:
y_pred   #Predicted Salary

array([ 41056.25705466, 123597.70938378,  65443.50433372,  63567.56223533,
       116093.94099022, 108590.17259667, 117031.91203942,  64505.53328452])

In [24]:
regressor.intercept_

26986.691316737248

In [25]:
regressor.coef_

array([9379.71049195])

In [26]:
from sklearn import metrics

In [27]:
r2score = metrics.r2_score(y_test,y_pred)

In [28]:
r2score  # This show efficency of algorithum

0.9779208335417602

In [29]:
accuracy = 0.97 * 100
accuracy

97.0

In [30]:
regressor.score(x,y)  # This show accuracy of data

0.955975487542377

In [31]:
tp = y_test - y_pred

In [32]:
tp

array([-3325.25705466, -1206.70938378, -8362.50433372,  -349.56223533,
         875.05900978,   840.82740333, -4396.91203942, -8711.53328452])

# Check predicted values

In [33]:
trial = pd.DataFrame(columns = ['yr_exp'])

In [34]:
trial

Empty DataFrame
Columns: [yr_exp]
Index: []

In [35]:
a  =  pd.Series([5.6,7.1,1])

In [36]:
trial['yr_exp'] = a

In [37]:
trial

yr_exp
0     5.6
1     7.1
2     1.0

In [38]:
b = trial['yr_exp'].values

In [39]:
b1 = b.reshape(-1,1)

In [40]:
y_pred = regressor.predict(b1)  

In [41]:
y_pred

array([79513.07007163, 93582.63580955, 36366.40180868])