In [54]:
import numpy as np

In [55]:
import pandas as pd

In [56]:
from pandas import Series,DataFrame

In [57]:
df = pd.read_csv('data.csv')

In [58]:
df

date         price  bedrooms  bathrooms  sqft_living  \
0     2014-05-02 00:00:00  3.130000e+05       3.0       1.50         1340   
1     2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650   
2     2014-05-02 00:00:00  3.420000e+05       3.0       2.00         1930   
3     2014-05-02 00:00:00  4.200000e+05       3.0       2.25         2000   
4     2014-05-02 00:00:00  5.500000e+05       4.0       2.50         1940   
...                   ...           ...       ...        ...          ...   
4595  2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510   
4596  2014-07-09 00:00:00  5.343333e+05       3.0       2.50         1460   
4597  2014-07-09 00:00:00  4.169042e+05       3.0       2.50         3010   
4598  2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090   
4599  2014-07-10 00:00:00  2.206000e+05       3.0       2.50         1490   

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
0         7912     1.5           0     0          3        1340   
1         9050     2.0           0     4          5        3370   
2        11947     1.0           0     0          4        1930   
3         8030     1.0           0     0          4        1000   
4        10500     1.0           0     0          4        1140   
...        ...     ...         ...   ...        ...         ...   
4595      6360     1.0           0     0          4        1510   
4596      7573     2.0           0     0          3        1460   
4597      7014     2.0           0     0          3        3010   
4598      6630     1.0           0     0          3        1070   
4599      8102     2.0           0     0          4        1490   

      sqft_basement  yr_built  yr_renovated                    street  \
0                 0      1955          2005      18810 Densmore Ave N   
1               280      1921             0           709 W Blaine St   
2                 0      1966             0  26206-26214 143rd Ave SE   
3              1000      1963             0           857 170th Pl NE   
4               800      1976          1992         9105 170th Ave NE   
...             ...       ...           ...                       ...   
4595              0      1954          1979            501 N 143rd St   
4596              0      1983          2009          14855 SE 10th Pl   
4597              0      2009             0          759 Ilwaco Pl NE   
4598           1020      1974             0         5148 S Creston St   
4599              0      1990             0         18717 SE 258th St   

           city  statezip country  
0     Shoreline  WA 98133     USA  
1       Seattle  WA 98119     USA  
2          Kent  WA 98042     USA  
3      Bellevue  WA 98008     USA  
4       Redmond  WA 98052     USA  
...         ...       ...     ...  
4595    Seattle  WA 98133     USA  
4596   Bellevue  WA 98007     USA  
4597     Renton  WA 98059     USA  
4598    Seattle  WA 98178     USA  
4599  Covington  WA 98042     USA  

[4600 rows x 18 columns]

In [59]:
del df['date']

In [60]:
del df['street']

In [61]:
del df['city']

In [62]:
del df['statezip']

In [63]:
del df['country']

In [64]:
df

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0     3.130000e+05       3.0       1.50         1340      7912     1.5   
1     2.384000e+06       5.0       2.50         3650      9050     2.0   
2     3.420000e+05       3.0       2.00         1930     11947     1.0   
3     4.200000e+05       3.0       2.25         2000      8030     1.0   
4     5.500000e+05       4.0       2.50         1940     10500     1.0   
...            ...       ...        ...          ...       ...     ...   
4595  3.081667e+05       3.0       1.75         1510      6360     1.0   
4596  5.343333e+05       3.0       2.50         1460      7573     2.0   
4597  4.169042e+05       3.0       2.50         3010      7014     2.0   
4598  2.034000e+05       4.0       2.00         2090      6630     1.0   
4599  2.206000e+05       3.0       2.50         1490      8102     2.0   

      waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0              0     0          3        1340              0      1955   
1              0     4          5        3370            280      1921   
2              0     0          4        1930              0      1966   
3              0     0          4        1000           1000      1963   
4              0     0          4        1140            800      1976   
...          ...   ...        ...         ...            ...       ...   
4595           0     0          4        1510              0      1954   
4596           0     0          3        1460              0      1983   
4597           0     0          3        3010              0      2009   
4598           0     0          3        1070           1020      1974   
4599           0     0          4        1490              0      1990   

      yr_renovated  
0             2005  
1                0  
2                0  
3                0  
4             1992  
...            ...  
4595          1979  
4596          2009  
4597             0  
4598             0  
4599             0  

[4600 rows x 13 columns]

In [65]:
#  x1 = df.iloc[:,1].values.reshape(-1,1)

In [66]:
#  x1

In [67]:
# x2 = df.iloc[:,2].values.reshape(-1,1)

In [68]:
# x2

In [69]:
# x3 = df.iloc[:,3].values.reshape(-1,1)

In [70]:
# x3

In [71]:
# x4 = df.iloc[:,4].values.reshape(-1,1)

In [72]:
# x4

In [73]:
# x9= df.iloc[:,9].values.reshape(-1,1)

In [74]:
# x9

In [75]:
# x10 = df.iloc[:,10].values.reshape(-1,1)

In [76]:
# x10

In [77]:
# x11 = df.iloc[:,11].values.reshape(-1,1)

In [78]:
# x11

In [79]:
# x12 = df.iloc[:,12].values.reshape(-1,1)

In [80]:
# x12

In [81]:
x = df.iloc[:,1:].values

In [82]:
x

array([[3.000e+00, 1.500e+00, 1.340e+03, ..., 0.000e+00, 1.955e+03,
        2.005e+03],
       [5.000e+00, 2.500e+00, 3.650e+03, ..., 2.800e+02, 1.921e+03,
        0.000e+00],
       [3.000e+00, 2.000e+00, 1.930e+03, ..., 0.000e+00, 1.966e+03,
        0.000e+00],
       ...,
       [3.000e+00, 2.500e+00, 3.010e+03, ..., 0.000e+00, 2.009e+03,
        0.000e+00],
       [4.000e+00, 2.000e+00, 2.090e+03, ..., 1.020e+03, 1.974e+03,
        0.000e+00],
       [3.000e+00, 2.500e+00, 1.490e+03, ..., 0.000e+00, 1.990e+03,
        0.000e+00]])

In [83]:
y = df.iloc[:,0].values

In [84]:
y

array([ 313000.      , 2384000.      ,  342000.      , ...,
        416904.166667,  203400.      ,  220600.      ])

In [85]:
from sklearn.model_selection import train_test_split

In [86]:
# x_train = x1_train,x2_train,x3_train,x4_train,x9_train,x10_train,x11_train

In [87]:
# x_test =x1_test,x2_test,x3_test,x4_test,x9_test,x10_test,x11_test

In [88]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.20,random_state = 0)

In [89]:
from sklearn.linear_model import LinearRegression

In [90]:
reg = LinearRegression()

In [91]:
reg.fit(x_train,y_train)

LinearRegression()

In [92]:
y_pred = reg.predict(x_test)

In [46]:
y_pred

array([ 509531.73334973,  631403.61913727,  245699.02163352,
        575057.46768666,  776352.89813186,  286065.15959556,
        603360.1576946 ,  616276.1442418 ,  350561.71471842,
       1336770.87332658,  587838.26192152,  446844.46842095,
       1024008.46565529,  538744.55839863,  600835.80292685,
        289312.67698769,  375678.04081206,  466786.05807093,
        941333.06911325,  370734.30425276,  421342.69998008,
        910449.85636337,  371470.42632192,  412855.53527861,
        720113.49599693,  436688.20671142,  636335.06798852,
        612757.01082834,  263803.89113819,  615749.53155079,
        734364.45648785,  487217.32678685,  515257.13387396,
        546046.12506498,  388985.16966014,  468707.68157388,
        351710.6697909 ,  415414.61154428,  409760.57232127,
        584723.48823141,  605253.65142945,  412533.5141789 ,
        504292.3907259 ,  798255.02443324,  404320.50054599,
        633649.34205362,  773867.24454002,  881644.90441499,
        543027.73872008,

In [47]:
z = y_test - y_pred

In [48]:
z

array([-2.20531733e+05, -2.01503619e+05, -1.16699022e+05,  2.49425323e+04,
        5.21647102e+05, -1.38065160e+05, -2.06860158e+05, -1.66276144e+05,
       -6.06171472e+03, -8.67708733e+04, -1.37038262e+05,  1.33155532e+05,
       -2.40084657e+04,  2.62554416e+04, -2.60845803e+05, -1.14312677e+05,
        4.54321959e+05, -5.67860581e+04,  6.38666931e+05, -1.85734304e+05,
        6.36573000e+04, -2.10449856e+05, -3.35246763e+04, -5.78555353e+04,
       -1.15113496e+05, -1.66882067e+04, -6.36335068e+05,  1.22429892e+04,
       -5.88038911e+04, -1.15799532e+05,  2.75635544e+05, -1.24173268e+04,
        2.76742866e+05,  1.33953875e+05,  4.60148303e+04,  6.19231843e+03,
       -1.97106698e+04, -1.56414612e+05,  2.80239428e+05, -5.47234882e+04,
       -2.15253651e+05, -4.35335142e+04, -9.82298907e+04,  1.64744976e+05,
        2.00679499e+05, -5.86493421e+04, -3.68867245e+05,  8.83550956e+04,
        1.01972261e+05, -1.33695646e+05, -1.11001381e+05,  2.99018341e+04,
        5.75956664e+04, -

In [49]:
reg.coef_

array([-5.87984645e+04,  6.62944843e+04,  1.59342738e+02, -6.75122633e-01,
        3.26880015e+04,  3.02689414e+05,  4.52571605e+04,  3.38848789e+04,
        8.76237239e+01,  7.17190141e+01, -2.27561204e+03,  6.67723595e+00])

In [50]:
reg.intercept_

4395948.751375914

In [51]:
from sklearn import metrics

In [52]:
acc = metrics.r2_score(y_test,y_pred)

In [53]:
acc *100

54.88458079132712